name: deploy

on:
  push:
    branches: [main]

concurrency: production_environment

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install dependencies
        run: cd ./ci && composer install

      - name: Deploy
        uses: deployphp/action@v1
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        with:
          private-key: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          dep: deploy
          sub-directory: ./ci
